### ISSUE TITLE
能不能对某一列自定义制表符和align

### ISSUE THREAD

**Issue by YifangSun** [liushuochen/gotable#3]
```
+----------+-----------------+------------+
|  China   |       US        |     UK     |
+----------+-----------------+------------+
| Beijing  | Washington D.C. |   London   |
|  Xi'AN   |     NewYork     | Manchester |
| Hangzhou |   Los Angeles   | Manchester |
+----------+-----------------+------------+
```
只有第二列左对齐，变成下面这样：↓
```
+----------+-----------------+------------+
|  China   |       US        |     UK     |
+----------+-----------------+------------+
| Beijing  | Washington D.C. |   London   |
|  Xi'AN   | NewYork         | Manchester |
| Hangzhou | Los Angeles     | Manchester |
+----------+-----------------+------------+
```
或者去掉边框：
```
  China            US               UK     
 Beijing    Washington  D.C.  London     
 Xi'AN      NewYork           Manchester 
 Hangzhou   Los Angeles       Manchester 
```

**Comment by liushuochen** [comment]
Hi, 关于你提到的左对齐和去掉边框这两个功能，gotable在之前的版本中就已实现。


你可以参考Readme中的API和Demo来获取相关的使用方法。
如果你使用的版本中没有相关的API，可以使用最新版本的gotable。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liushuochen/gotable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 下午4:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[liushuochen/gotable] 能不能自定义制表符和align (#3)





 +----------+-----------------+------------+ |  China   |       US        |     UK     | +----------+-----------------+------------+ | Beijing  | Washington D.C. |   London   | |  Xi'AN   |     NewYork     | Manchester | | Hangzhou |   Los Angeles   | Manchester | +----------+-----------------+------------+  
左对齐，变成下面这样：↓
 +----------+-----------------+------------+ |  China   |       US        |     UK     | +----------+-----------------+------------+ | Beijing  | Washington D.C. | London     | | Xi'AN    | NewYork         | Manchester | | Hangzhou | Los Angeles     | Manchester | +----------+-----------------+------------+  
或者去掉边框：
   China            US               UK       Beijing    Washington  D.C.  London       Xi'AN      NewYork           Manchester   Hangzhou   Los Angeles       Manchester   
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YifangSun** [comment]
我仔细看了demo，功能都有。issue关了

**Comment by YifangSun** [comment]
@liushuochen 功能很好用。
 
但是有没有更方便一点设置row的方法呢？比如像tabwriter一样一次输入一整行。
另外还有些使用场景是要一次设置一列的值（行数已经固定了）。
 
这些问题好像使用的时候，我自己手动用map包起来都可以实现，但是感觉还是集成在库里面比较安全和方便。

**Comment by liushuochen** [comment]
Hi, 我总结下你的邮件:
希望添加row的时候采用Slice的方式，Slice中的值顺序是按照Column的顺序来对应的，而不是采用Map的方式。


如果是这个需求的话可以考虑在后续的版本中添加AddRowFromSclice这个API来提供对这种场景的支持。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liushuochen/gotable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 下午5:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liushuochen/gotable] 能不能对某一列自定义制表符和align (#3)





 
@liushuochen 功能很好用。
 
但是有没有更方便一点设置row的方法呢？比如像tabwriter一样一次输入一整行。
 另外还有些使用场景是要一次设置一列的值（行数已经固定了）。
 
这些问题好像使用的时候，我自己手动用map包起来都可以实现，但是感觉还是集成在库里面比较安全和方便。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YifangSun** [comment]
是的。

**Comment by YifangSun** [comment]
昨天我在使用的时候发现，如果关了border，左边一列右对齐，右边一列左对齐，会出现两列之间完全相连的情况。如图：
 
![image](https://user-images.githubusercontent.com/39836849/133736440-e0661674-d6a4-47b0-8d23-13109fc954e9.png)

所以我刚改了代码。关了border的时候，我把border变成了一个空格，于是每个cell填充的两个空格就不再必要。
 
![image](https://user-images.githubusercontent.com/39836849/133738223-a60a793d-6c4a-4d92-84f3-75cd717b7352.png)

刚提了一个pr，你看下有没有用

**Comment by liushuochen** [comment]
收到～






------------------ 原始邮件 ------------------
发件人: 孙逸方 ***@***.***&gt;
发送时间: 2021年9月17日 15:00
收件人: liushuochen/gotable ***@***.***&gt;
抄送: TCatTime ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[liushuochen/gotable] 能不能对某一列自定义制表符和align (#3)





 
昨天我在使用的时候发现，如果关了border，左边一列右对齐，右边一列左对齐，会出现两列之间完全相连的情况。如图：
 

 
所以我刚改了代码。关了border的时候，我把border变成了一个空格，于是每个cell填充的两个空格就不再必要。
 

 
刚提了一个pr，你看下有没有用
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liushuochen** [comment]
> 是的。

Hi, 在Gotable 4.2.0中支持了使用Slice添加row的功能。这个改动涉及了API:  *table.AddRow，新的*table.AddRow参数不再是map[string]string，而是一个interface{}。在新的API中支持了Slice和Map两种数据类型，保留了老版本添加row方式的同时也达到了支持Slice的作用。更多的使用方法可以参考 gotable 4.2.0中的README.md

**Comment by YifangSun** [comment]
> Hi, 在Gotable 4.2.0中支持了使用Slice添加row的功能。这个改动涉及了API: _table.AddRow，新的_table.AddRow参数不再是map[string]string，而是一个interface{}。在新的API中支持了Slice和Map两种数据类型，保留了老版本添加row方式的同时也达到了支持Slice的作用。更多的使用方法可以参考 gotable 4.2.0中的README.md

中秋快乐！刚看到，作者开发效率很高。
 
我也觉得用interface会好一些，具体的我使用完再来评论 ^_^
